### ISSUE TITLE
Parts exploding when attached to ground

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Surface-Experiment-Pack#3]
Apparently parts go boom boom
EDIT: Parts also do not actually attach to the ground. They merely drop.

**Comment by Ruedii** [comment]
Likely occurs when terrain shape prevents parts from properly attaching to ground.

There are several ways to improve this: 
1. Use partbreak module (like solar panels) on impact instead of making them explode.  (This module is great for any sensitive instruments, and is underused by mods as well as Stock KSP.)  This will allow engineers to fix them.  :+1:   It also makes sure the joints aren't affected by breaking.
2. increase the impact tolerance.
3.  Add leg animations and use the landing gear modules with wheelstress and wheelbreak modules instead of crash tolerance modules.  This is like 1 but with much more functionality. 

As a note, there are a series of physics transition bugs that Squad is fixing that are known to cause G-Spikes on some parts.  This may be the source of the bug.

**Comment by CobaltWolf** [comment]
@Ruedii I've already increased the impact tolerance immensely. What I REALLY need is a way to increase the strength of the joint to the ground, or even somehow making it unbreakable.

**Comment by CobaltWolf** [comment]
@Ruedii I managed to fix this, details on what was causing it are on the thread. It is fixed in v1.4.2
https://github.com/CobaltWolf/Surface-Experiment-Pack/commit/e5f476142ad692b072411e400d133dc1bbaa6412

**Comment by Ruedii** [comment]
I'll do some grocking of config files later on to find the right variable.
Hopefully it is one exposed in the files, even if it isn't always present
by default.

**Comment by CobaltWolf** [comment]
@Ruedii I fixed this issue last night, SEP is working with no explosions!

**Comment by Ruedii** [comment]
Now it's just not connecting sometime.

Better, not perfect.  

Have you considered changing the connection node size up to the next size?  This should default the connection range to be a little further.  Also, try inching the node out a tiny bit from the base collider. 

These two hacks are the best we can do without physically editing the collider or having to file an upstream fix with Kerbal Inventory System / Kerbal Attachment System.

**Comment by DMagic1** [comment]
Open a new issue if it isn't related to exploding parts, otherwise it will just get lost.
